apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/sbinkhalid-palo-it-com/hash-it-frontend:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/sbinkhalid-palo-it-com/hash-it-frontend:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: hash-it-frontend
        chartPath: charts/hash-it-frontend
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/sbinkhalid-palo-it-com/hash-it-frontend"
          image.tag: "{{.DIGEST_HEX}}"
