FROM williamyeh/ansible:ubuntu16.04

RUN apt-get update -y
RUN apt-get install curl -y
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y iputils-ping
RUN apt-get install -y git
RUN apt-get install -y ssh
RUN apt-get install -y vim

